apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpnM05UQXhNamN3SGhjTk1qWXdNVEU0TVRVeU9EUTNXaGNOTXpZd01URTJNVFV5T0RRMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpnM05UQXhNamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRckJtMTgwSHlEOUhtRGpWNjA4RzBkU0xJRktuNWc5N0syZjZNNUsyalUKczk1MzhoR0RlMkw4THI0QWNMOGlRNVZHNXpVVWx2N2cxbEhDdzgxUi92ek5vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXB4TUxQbmE5OC9HTUFTcEphdWpOCmxuMzdnM013Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTmtrZkNQdzhnK3UvUFoxZU1HN0pLYzBlNURXV20vb2cKK0J2TmZxOHFCeEVDSUM0Unl5V0F4cTgxOGRZSVpqbUp6cERrTGgwZFpmSkVRTkFFUjA1MStTWWIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:6443
  name: Mehdi
contexts:
- context:
    cluster: Mehdi
    user: Mehdi-sa
  name: Mehdi
current-context: Mehdi
kind: Config
users:
- name: Mehdi-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjlSaWhSLUZuejVDOUxGdDJYWEZsMEttMHFwWjQ0X3AtM25GQzJxNWI1RkEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY5MDE0MjQ0LCJpYXQiOjE3Njg5Mjc4NDQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNzQyOTlhMTAtNTQyMi00M2M1LTlmYWUtODAyNTE1NmVhYTgwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhZG1pbi1zYSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi1zYSIsInVpZCI6Ijg1NzY3NDM1LTgyNzgtNDA2Yy1iNTYzLTZjMzcyZmY2OGNlNSJ9fSwibmJmIjoxNzY4OTI3ODQ0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YWRtaW4tc2E6YWRtaW4tc2EifQ.LUpqIDKaG2ARIds8rrLA4VhZf2Sn5zRsvJ4GPpS4YRblB49MrIkpnP7UaiGfxBKEDigLV1pO85VWpo4sYWOj8Ch2ReN-hXH74n3Jf1TwDuQ9ZRFDtCOQFzFWIqNqlpcgAJd0LjE4_Tk7mQ12IImAVdveJ9C0hrRZEd-6OL89HoBHDUb_Q_GZkuHAlbyOgP51OK7CxHm9rEiCkotIfvADK2jtSvgHq1NUiSn_sv2gFFq1ujWC2Q4dXdn0C9wWvhISq7a8kcIhdQejOGvgPd1moOEAvMpTJq9ioYUA4F8BjOli3EB443srbxseZcBGIv2E1O3eu0t3oTgIhAXozR1omg
